### PR TITLE
Fix typo 'in-pad' --> 'pin-pad'

### PR DESCRIPTION
**Pull request by austin-bowen**
`README.md` and `raspi-gpio.c ` contain typo 'in-pad' which should be 'pin-pad'.

### CODE REVIEW

**Comment by pelwell** [comment]
I agree that there is inconsistency, but I don't think this is the correct "fix". Winding all the way back to May 2015 to when some examples were added you find the following [ from
https://github.com/RPi-Distro/raspi-gpio/blob/d07666d68f95b0ee3b91606e8fcece7ca2138c95/gpiostate.c#L265 ]
```
  printf("  pu      set GPIO in-pad pull up\n");
  printf("  pd      set GPIO pin-pad pull down\n");
  printf("  pn      set GPIO pull none (no pull)\n");
  printf("  dh      set GPIO to drive to high (1) level (only valid if set to be an output)\n");
  printf("  dl      set GPIO to drive low (0) level (only valid if set to be an output)\n");
  printf("Examples:\n");
  printf("  %s get              Prints state of all GPIOs one per line\n", name);
  printf("  %s get 20           Prints state of GPIO20\n", name);
  printf("  %s set 20 a5        Set GPIO20 to ALT5 function (GPCLK0)\n", name);
  printf("  %s set 20 pu        Enable GPIO20 ~50k in-pad pull up\n", name);
  printf("  %s set 20 pd        Enable GPIO20 ~50k in-pad pull down\n", name);
```
Notice how the pull up and pull down example both refer to "in-pad". "pin-pad" isn't a term I recognise, while I can see the logic behind the name "in-pad", as in "the I/O pad when in input mode" (which is when the pull really matters.

**Comment by ghollingworth** [comment]
Specifically 'in-pad pullup' refers to the pullup in the pad (the bit of the silicon that implements the physical pad electronics) , rather than any external pullup...

**Comment by pelwell** [comment]
Duh! Yes, of course.

**Comment by pelwell** [comment]
Fixed by 94f77d5.

**Comment by austin-bowen** [comment]
@pelwell Ah okay that makes sense, I really wasn't sure either way :) I see you fixed it in `raspi-gpio.c`, but the typo remains in the README.

**Pull request closed without merging**
