### PR TITLE
feat: Update raw output to include all 2711 registers

### PR DESCRIPTION
**Pull request by rwhelan**

### CODE REVIEW

**Comment by pelwell** [comment]
What's the motivation behind this change? There are a load of extra registers that would be included in this dump that aren't relevant to a Pi4.

**Comment by rwhelan** [comment]
The motivation is, I found the tool lacking when trying to use it to diagnose an issue with my applications handling of Pi4 pullup/pulldown resister config.  The registers used to manage the pull states were outside the range of the raw output.

**Comment by pelwell** [comment]
I would prefer it if the intermediate registers were skipped.

**Comment by rwhelan** [comment]
> I would prefer it if the intermediate registers were skipped.

I took a stab at it.  I'm _far_ from even a C novice; it might not be very idiomatic.

**Comment by pelwell** [comment]
The way you had it originally was cleaner, so I've patched it to add the skip functionality.

**Pull request merged**
